### ISSUE TITLE
Random Crashes on Linux

### ISSUE THREAD

**Issue by CrazyCoder** [ShyykoSerhiy/gfm-plugin#125]
https://youtrack.jetbrains.com/issue/IDEA-178525

```
"AWT-EventQueue-0 2017.2.3#IU-172.3968.16 IDEA, eap:false, os:Linux 4.12.6-1-arch, java-version:JetBrains s.r.o 1.8.0_152-release-915-b11" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on java.util.concurrent.CountDownLatch$Sync@48e1df65
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
    at com.teamdev.jxbrowser.chromium.internal.ipc.LatchUtil.await(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.ipc.LatchUtil.await(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.stop(Unknown Source)
    at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
    at com.teamdev.jxbrowser.chromium.Browser.dispose(Unknown Source)
    at com.github.shyykoserhiy.gfm.browser.BrowserJx$4.run(BrowserJx.java:67)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by fgblomqvist** [comment]
Unfortunately, these crashes are making it pretty much impossible to use this plugin on Linux. Is there anything we can do to help with getting this resolved?

**Comment by ShyykoSerhiy** [comment]
I'm going to bump jxbrowser version. It should resolve the issue.

**Comment by fgblomqvist** [comment]
@ShyykoSerhiy Any update on this? Seems like a trivial task but due to their licensing model I can't help with it.

**Comment by ShyykoSerhiy** [comment]
@fgblomqvist should be fixed around next week

**Comment by Ghedeon** [comment]
Any progress on this? Seems to be reproducible on `#AI-181.5540.7.32.5056338` 
https://issuetracker.google.com/issues/120157997

**Comment by akapps** [comment]
It seems to work better for me now (v. `0.1.14`), I can visualize markdown files. But I still get a crash, this time after I close the gfm renderer, with the following stacktrace :
```
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to execute shutdown post message.
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.stop(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.dispose(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx$4.run(BrowserJx.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It might be a `jxbrowser` issue though, unless you are in control of the "shutdown post message"...
